/**
 * PPF contract types — generated by PPB's OpenAPI (openapi-typescript).
 *
 * SYNC: when PPB updates its OpenAPI, re-run `scripts/gen-types.sh` to copy the
 * latest `ppb/contracts/types.ts` here. Do NOT hand-edit this file.
 *
 * AUTHORITATIVE: these are the frozen contract types (snake_case, contract §20).
 * Handwritten refinements in `src/utils/api/types.ts` must not conflict; where
 * they do, the generated types win.
 *
 * NOTE: only the `components` interface is kept (paths/operations are dropped
 * because PPB currently reuses generic operationIds, which would produce
 * duplicate TS identifiers). Fix operationIds in PPB OpenAPI to restore them.
 */

export interface components {
    schemas: {
        ActionBody: {
            action: string;
        };
        AdminRoomActionBody: {
            action: string;
            args?: unknown;
        };
        BroadcastBody: {
            content: string;
            room_id?: string | null;
            /** Format: int64 */
            user_id?: number | null;
        };
        ChangePasswordRequest: {
            current_password?: string | null;
            new_password: string;
        };
        ChatSendBody: {
            content: string;
        };
        ConfigContentBody: {
            content: string;
            note?: string;
        };
        CreateCouponBody: {
            action_type: string;
            code?: string;
            /** Format: int32 */
            max_uses?: number | null;
            payload?: unknown;
        };
        CreateGroupBody: {
            description?: string;
            name: string;
        };
        CreateJobBody: {
            args?: unknown;
            type: string;
        };
        CreateRoomBody: {
            endpoint?: string | null;
            persistent_empty?: boolean;
            room_id: string;
        };
        CreateRunbookBody: {
            definition: components["schemas"]["RunbookDefinition"];
            description?: string;
            name: string;
        };
        /** @description Serializable error body (`error` member). */
        ErrorBody: {
            code: string;
            details: unknown;
            message: string;
            request_id: string;
        };
        /** @description Wrapper for the JSON `{ "error": ... }` envelope. */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        ExecuteActionBody: {
            args?: unknown;
        };
        ExecuteCommandBody: {
            command: string;
        };
        InputBody: {
            text: string;
        };
        JoinIntentBody: {
            room_id: string;
            /** Format: int64 */
            ttl_secs?: number | null;
        };
        LogInputBody: {
            command: string;
        };
        /** @description `GET /api/v1/me` session-probe response (S-4). */
        MeResponse: {
            capabilities: string[];
            csrf_token: string;
            identities?: unknown;
            permissions: string[];
            phira_credential?: unknown;
            principal: unknown;
            session: unknown;
            user?: unknown;
        };
        /** @description Standard paginated response `{items, total, page, pageNum}`. */
        PaginationResponse: {
            items: unknown[];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            pageNum: number;
            /** Format: int64 */
            total: number;
        };
        PhiraLoginRequest: {
            client_type?: string | null;
            device_name?: string | null;
            email: string;
            password: string;
            return_to?: string | null;
        };
        PluginCallBody: {
            args?: unknown[];
            method?: string;
            name: string;
        };
        PushEndpointBody: {
            channel: string;
            device_id: string;
            platform?: string;
            subscription: components["schemas"]["SubscriptionWire"];
        };
        ReauthRequest: {
            client_type?: string | null;
            email?: string | null;
            password: string;
            risk?: string | null;
        };
        RenameGroupBody: {
            name: string;
        };
        ReplaceMembersBody: {
            user_ids: string[];
        };
        ReplacePermissionsBody: {
            permissions: string[];
        };
        /** @description Replay detail (summary + visibility). */
        ReplayDetail: {
            judges: unknown;
            /** Format: int64 */
            player_phira_id: number;
            round_uuid: string;
            touches: unknown;
            visibility: string;
        };
        /** @description Replay manifest summary (per `(round_uuid, player_phira_id)` pair). */
        ReplayManifest: {
            judges: unknown;
            /** Format: int64 */
            player_phira_id: number;
            round_uuid: string;
            touches: unknown;
        };
        RollbackBody: {
            /** Format: uuid */
            snapshot_id: string;
        };
        RoomActionBody2: {
            action: string;
            args?: unknown;
        };
        /** @description Room action request `{action, args}`. */
        RoomActionRequest: {
            action: string;
            args?: unknown;
        };
        RoomBatchBody: {
            action: string;
            args?: unknown;
            room_ids: string[];
        };
        RoomCreationBody: {
            enabled: boolean;
        };
        RootLoginRequest: {
            password: string;
        };
        /** @description A runbook definition (stored as JSONB; snapshot on every run). */
        RunbookDefinition: {
            args?: unknown;
            description?: string;
            name: string;
            steps: components["schemas"]["RunbookStep"][];
        };
        RunbookStep: {
            /** @description Empty for a WAIT-only step (design §10.1 `wait: <secs>`). */
            action?: string;
            /**
             * Format: int64
             * @description `wait_secs` accepts both `wait_secs` and `wait` keys.
             */
            wait?: number | null;
            with?: unknown;
        };
        SendBody: {
            body?: string;
            payload?: unknown;
            priority?: string;
            /** @description `{ "all": true }` | `{ "group_id": "<uuid>" }` | `{ "user_ids": [...] }` */
            target?: unknown;
            title?: string;
            type: string;
        };
        SendRequestBody: {
            /** Format: int64 */
            phira_id: number;
        };
        ServerActionBody: {
            action: string;
            args?: unknown;
        };
        /** @description Encrypted subscription wire shape (before encryption at rest). */
        SubscriptionWire: {
            auth: string;
            endpoint: string;
            p256dh: string;
        };
        TranslateParams: {
            code: string;
        };
        UpdatePreferencesBody: {
            /** Format: int64 */
            base_revision?: number | null;
            data: unknown;
        };
        UserActionBody: {
            action: string;
            args?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
