/**
 * PPF contract types — generated by PPB's OpenAPI (openapi-typescript).
 *
 * SYNC: when PPB updates its OpenAPI, re-run `scripts/gen-types.sh` to copy the
 * latest `ppb/contracts/types.ts` here. Do NOT hand-edit this file.
 *
 * AUTHORITATIVE: these are the frozen contract types (snake_case, contract §20).
 * Handwritten refinements in `src/utils/api/types.ts` must not conflict; where
 * they do, the generated types win.
 *
 * NOTE: only the `components` interface is kept (paths/operations are dropped
 * because PPB currently reuses generic operationIds, which would produce
 * duplicate TS identifiers). Fix operationIds in PPB OpenAPI to restore them.
 */

export interface components {
    schemas: {
        ActionBody: {
            action: string;
        };
        AdminRoomActionBody: {
            action: string;
            args?: unknown;
        };
        /**
         * @description Admin user list/detail wire item (§22: `ppb_user_id` UUID, `phira_id`,
         *     `username`/`avatar` naming aligned with Panel).
         */
        AdminUserItem: {
            avatar: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            /** Format: int64 */
            phira_id: number;
            /** Format: uuid */
            ppb_user_id: string;
            status: string;
            /** Format: date-time */
            updated_at: string;
            username: string;
        };
        /** @description Wire shape of one inbox notification (contract §8). */
        AppNotificationWire: {
            actions: unknown[];
            actor: unknown;
            body?: unknown;
            /** Format: date-time */
            created_at: string;
            dedup_key: string;
            deep_link: string;
            expires_at?: unknown;
            /** Format: uuid */
            id: string;
            input?: unknown;
            priority: string;
            /** Format: date-time */
            read_at?: string | null;
            target: unknown;
            title: string;
            type: string;
        };
        AuditEvent: {
            action: string;
            /** Format: uuid */
            actor_session_id?: string | null;
            /** Format: uuid */
            actor_user_id?: string | null;
            command_id: string;
            error_code: string;
            /** Format: uuid */
            id: string;
            ip: string;
            /** Format: date-time */
            occurred_at: string;
            parameters_redacted: unknown;
            principal_type: string;
            request_id: string;
            resource_id: string;
            resource_type: string;
            result: string;
            user_agent: string;
        };
        /** @description Paginated audit list response (§22 `{items, total, page, pageNum}`). */
        AuditListResponse: {
            items: components["schemas"]["AuditEvent"][];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            pageNum: number;
            /** Format: int64 */
            total: number;
        };
        BroadcastBody: {
            content: string;
            room_id?: string | null;
            /** Format: int64 */
            user_id?: number | null;
        };
        ChangePasswordRequest: {
            current_password?: string | null;
            new_password: string;
        };
        ChatSendBody: {
            content: string;
        };
        /**
         * @description A PMP config field descriptor (Panel renders grouped forms). Schema-freeze
         *     (§22): descriptor carries type/widget/min/max/risk/permission/reload
         *     semantics/sensitive/default.
         */
        ConfigFieldDescriptor: {
            default?: unknown;
            description: string;
            label: string;
            /** Format: double */
            max?: number | null;
            /** Format: double */
            min?: number | null;
            /** Format: int32 */
            order: number;
            path: string;
            permission: string;
            /** @description hot | restart | rebuild */
            reload_semantics: string;
            risk: string;
            sensitive: boolean;
            /** @description Wire type: `string | number | boolean`. */
            type: string;
            widget: string;
        };
        /** @description A named group of related config fields (Panel renders per group). */
        ConfigFieldGroup: {
            fields: components["schemas"]["ConfigFieldDescriptor"][];
            key: string;
            label: string;
        };
        ConfigSnapshot: {
            content: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            created_by?: string | null;
            /** Format: uuid */
            id: string;
            note: string;
            /** Format: date-time */
            restored_at?: string | null;
            scope: string;
        };
        /**
         * @description Form-value edit body (§22 model A): Panel submits `{path: value}` and PPB
         *     validates/generates YAML/saves.
         */
        ConfigValuesBody: {
            note?: string;
            values: unknown;
        };
        CreateCouponBody: {
            action_type: string;
            code?: string;
            /** Format: int32 */
            max_uses?: number | null;
            payload?: unknown;
        };
        CreateGroupBody: {
            description?: string;
            name: string;
        };
        CreateJobBody: {
            args?: unknown;
            type: string;
        };
        CreateRoomBody: {
            endpoint?: string | null;
            persistent_empty?: boolean;
            room_id: string;
        };
        CreateRunbookBody: {
            definition: components["schemas"]["RunbookDefinition"];
            description?: string;
            name: string;
        };
        /** @description Serializable error body (`error` member). */
        ErrorBody: {
            code: string;
            details: unknown;
            message: string;
            request_id: string;
        };
        /** @description Wrapper for the JSON `{ "error": ... }` envelope. */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        ExecuteActionBody: {
            args?: unknown;
        };
        ExecuteCommandBody: {
            command: string;
        };
        Group: {
            /** Format: date-time */
            created_at: string;
            description: string;
            /** Format: uuid */
            id: string;
            is_default: boolean;
            name: string;
            protected: boolean;
            system_kind?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Typed group list item (§22: group fields + member_count + permissions). */
        GroupListItem: {
            /** Format: date-time */
            created_at: string;
            description: string;
            /** Format: uuid */
            id: string;
            is_default: boolean;
            /** Format: int64 */
            member_count: number;
            name: string;
            permissions: string[];
            protected: boolean;
            system_kind?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Paginated group list response (§22: `{items, total, page, pageNum}`). */
        GroupListResponse: {
            items: components["schemas"]["GroupListItem"][];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            pageNum: number;
            /** Format: int64 */
            total: number;
        };
        /** @description A group member with the PPB account display fields. */
        GroupMember: {
            /** Format: int64 */
            phira_id: number;
            /** Format: uuid */
            user_id: string;
            username: string;
        };
        InputBody: {
            text: string;
        };
        Job: {
            /** Format: date-time */
            created_at: string;
            error: string;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: uuid */
            id: string;
            /** Format: float */
            progress?: number | null;
            stage: string;
            /** Format: date-time */
            started_at?: string | null;
            state: string;
            type: string;
        };
        JoinIntentBody: {
            room_id: string;
            /** Format: int64 */
            ttl_secs?: number | null;
        };
        LogInputBody: {
            command: string;
        };
        /** @description `GET /api/v1/me` session-probe response (S-4). */
        MeResponse: {
            capabilities: string[];
            csrf_token: string;
            identities?: unknown;
            permissions: string[];
            phira_credential?: unknown;
            principal: unknown;
            session: unknown;
            user?: unknown;
        };
        /** @description Inbox response (§22 `{items, total, page, pageNum, unread}`). */
        NotificationInboxResponse: {
            items: components["schemas"]["AppNotificationWire"][];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            pageNum: number;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            unread: number;
        };
        /** @description Standard paginated response `{items, total, page, pageNum}`. */
        PaginationResponse: {
            items: unknown[];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            pageNum: number;
            /** Format: int64 */
            total: number;
        };
        PhiraLoginRequest: {
            client_type?: string | null;
            device_name?: string | null;
            email: string;
            password: string;
            return_to?: string | null;
        };
        PluginCallBody: {
            args?: unknown[];
            method?: string;
            name: string;
        };
        /** @description Typed PMP connectivity summary (server status). */
        PmpStatus: {
            connected: boolean;
            session_id?: string | null;
            version?: string | null;
        };
        /** @description Preferences list response (§22). */
        PreferencesListResponse: {
            preferences: components["schemas"]["UserPreference"][];
        };
        PushEndpointBody: {
            channel: string;
            device_id: string;
            platform?: string;
            subscription: components["schemas"]["SubscriptionWire"];
        };
        ReauthRequest: {
            client_type?: string | null;
            email?: string | null;
            password: string;
            risk?: string | null;
        };
        RenameGroupBody: {
            name: string;
        };
        ReplaceMembersBody: {
            user_ids: string[];
        };
        ReplacePermissionsBody: {
            permissions: string[];
        };
        /** @description Replay detail (summary + visibility). */
        ReplayDetail: {
            judges: unknown;
            /** Format: int64 */
            player_phira_id: number;
            round_uuid: string;
            touches: unknown;
            visibility: string;
        };
        /** @description Replay manifest summary (per `(round_uuid, player_phira_id)` pair). */
        ReplayManifest: {
            judges: unknown;
            /** Format: int64 */
            player_phira_id: number;
            round_uuid: string;
            touches: unknown;
        };
        RollbackBody: {
            /** Format: uuid */
            snapshot_id: string;
        };
        RoomActionBody2: {
            action: string;
            args?: unknown;
        };
        /** @description Room action request `{action, args}`. */
        RoomActionRequest: {
            action: string;
            args?: unknown;
        };
        RoomBatchBody: {
            action: string;
            args?: unknown;
            room_ids: string[];
        };
        RoomCreationBody: {
            enabled: boolean;
        };
        RootLoginRequest: {
            password: string;
        };
        /** @description A runbook definition (stored as JSONB; snapshot on every run). */
        RunbookDefinition: {
            args?: unknown;
            description?: string;
            name: string;
            steps: components["schemas"]["RunbookStep"][];
        };
        RunbookStep: {
            /** @description Empty for a WAIT-only step (design §10.1 `wait: <secs>`). */
            action?: string;
            /**
             * Format: int64
             * @description `wait_secs` accepts both `wait_secs` and `wait` keys.
             */
            wait?: number | null;
            with?: unknown;
        };
        SendBody: {
            body?: string;
            payload?: unknown;
            priority?: string;
            /** @description `{ "all": true }` | `{ "group_id": "<uuid>" }` | `{ "user_ids": [...] }` */
            target?: unknown;
            title?: string;
            type: string;
        };
        SendRequestBody: {
            /** Format: int64 */
            phira_id: number;
        };
        ServerActionBody: {
            action: string;
            args?: unknown;
        };
        /** @description Typed server status response (§22). */
        ServerStatusResponse: {
            db_configured: boolean;
            metrics: unknown;
            pmp: components["schemas"]["PmpStatus"];
            ppb_version: string;
        };
        /** @description Encrypted subscription wire shape (before encryption at rest). */
        SubscriptionWire: {
            auth: string;
            endpoint: string;
            p256dh: string;
        };
        TranslateParams: {
            code: string;
        };
        UpdatePreferencesBody: {
            /** Format: int64 */
            base_revision?: number | null;
            data: unknown;
        };
        UserActionBody: {
            action: string;
            args?: unknown;
        };
        /** @description User detail response (§22 `{account, groups, player}`). */
        UserDetailResponse: {
            account: components["schemas"]["AdminUserItem"];
            groups: string[];
            /** @description Best-effort PMP player info (dynamic payload; null when PMP offline). */
            player?: unknown;
        };
        /** @description Paginated user list response (§22 `{items, total, page, pageNum}`). */
        UserListResponse: {
            items: components["schemas"]["AdminUserItem"][];
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            pageNum: number;
            /** Format: int64 */
            total: number;
        };
        UserPreference: {
            data: unknown;
            namespace: string;
            /** Format: int64 */
            revision: number;
            /** Format: date-time */
            updated_at: string;
            /** Format: uuid */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
