#!/usr/bin/env bash
# Sync PPF contract types from the PPB repo's OpenAPI output.
#
# Source: <repo-root>/ppb/contracts/types.ts (generated by PPB via
# openapi-typescript). Run this whenever PPB updates its OpenAPI, then commit
# the refreshed `src/utils/api/generated.ts`.
#
# Usage:
#   scripts/gen-types.sh [path-to-ppb-types.ts]
set -euo pipefail

PPF_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$PPF_ROOT/src/utils/api/generated.ts"

# Default source: sibling ppb repo (adjust if your checkout differs).
SRC="${1:-$PPF_ROOT/../ppb/contracts/types.ts}"

if [[ ! -f "$SRC" ]]; then
  echo "error: source not found: $SRC" >&2
  echo "pass the path to ppb/contracts/types.ts as \$1" >&2
  exit 1
fi

cp "$SRC" "$DEST"
echo "✓ synced contract types -> $DEST"
echo "  (file is auto-generated; do not hand-edit)"
