#!/usr/bin/env bash
# Sync PPF contract types from the PPB repo's OpenAPI output.
#
# Source: <repo-root>/ppb/contracts/types.ts (generated by PPB via
# openapi-typescript). Run this whenever PPB updates its OpenAPI, then commit
# the refreshed `src/utils/api/generated.ts`.
#
# The PPB OpenAPI currently reuses generic operationIds (list/create/update/…)
# across resources, which produces an invalid TS `operations` interface. PPF
# only consumes `components['schemas']`, so this script keeps ONLY the
# `components` interface (paths/operations are dropped). Fix in PPB OpenAPI
# (unique operationIds) to restore the full type surface.
#
# Usage:
#   scripts/gen-types.sh [path-to-ppb-types.ts]
set -euo pipefail

PPF_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$PPF_ROOT/src/utils/api/generated.ts"

# Default source: sibling ppb repo (adjust if your checkout differs).
SRC="${1:-$PPF_ROOT/../ppb/contracts/types.ts}"

if [[ ! -f "$SRC" ]]; then
  echo "error: source not found: $SRC" >&2
  echo "pass the path to ppb/contracts/types.ts as \$1" >&2
  exit 1
fi

python3 - "$SRC" "$DEST" <<'PY'
import re, sys
src, dest = sys.argv[1], sys.argv[2]
txt = open(src, encoding='utf-8').read()

# Extract the balanced `export interface components { ... }` block.
m = re.search(r'export interface components \{\n', txt)
if not m:
    print('error: no components interface found', file=sys.stderr)
    sys.exit(1)

start = m.start()
# Count braces to find the matching close.
depth = 0
i = txt.index('{', start)
j = i
while j < len(txt):
    if txt[j] == '{':
        depth += 1
    elif txt[j] == '}':
        depth -= 1
        if depth == 0:
            break
    j += 1
block = txt[start:j + 1]

header = (
    "/**\n"
    " * PPF contract types — generated by PPB's OpenAPI (openapi-typescript).\n"
    " *\n"
    " * SYNC: when PPB updates its OpenAPI, re-run `scripts/gen-types.sh` to copy the\n"
    " * latest `ppb/contracts/types.ts` here. Do NOT hand-edit this file.\n"
    " *\n"
    " * AUTHORITATIVE: these are the frozen contract types (snake_case, contract §20).\n"
    " * Handwritten refinements in `src/utils/api/types.ts` must not conflict; where\n"
    " * they do, the generated types win.\n"
    " *\n"
    " * NOTE: only the `components` interface is kept (paths/operations are dropped\n"
    " * because PPB currently reuses generic operationIds, which would produce\n"
    " * duplicate TS identifiers). Fix operationIds in PPB OpenAPI to restore them.\n"
    " */\n\n"
)
open(dest, 'w', encoding='utf-8').write(header + block + '\n')
print(f'✓ synced contract types -> {dest}')
print('  (components only; paths/operations dropped — see note above)')
PY
